import "./styles.css"
import "@fontsource/baloo-tamma-2/400.css"
import "@fontsource/baloo-tamma-2/500.css"
import "@fontsource/baloo-tamma-2/600.css"
import "@fontsource/baloo-tamma-2/700.css"
import "@fontsource/baloo-tamma-2/800.css"